project:
  type: book

book:
  title: "Reaching for Infinity"
  author: "Steve Trettel"
  date: today
  downloads: [pdf]
  
  chapters:
    - index.qmd
    
    - part: "Numbers"
      chapters:
        - chapters/01-foundations/index.qmd
        - chapters/02-limits/index.qmd
        - chapters/03-theory-convergence/index.qmd
        - chapters/04-infinite-processes/index.qmd
        - chapters/05-exchanging-limits/index.qmd
        
    - part: "Functions"
      chapters:
        - chapters/06-continuity/index.qmd
        - chapters/07-differentiation/index.qmd
        - chapters/08-integration/index.qmd
        - chapters/09-calculus/index.qmd
        - chapters/10-extending-integral/index.qmd

    - part: "Function Space"
      chapters:
        - chapters/11-metrics/index.qmd
        - chapters/12-function-space/index.qmd
        - chapters/13-fourier/index.qmd
        - chapters/14-diffeq/index.qmd
        - chapters/15-distributions/index.qmd

    - coda.qmd


format:
  stevejtrettel/course-notes-html:
    include-before-body: 
       - "_formatting/dollar.tex"
       - "_formatting/macros.tex"
       - "_formatting/dollar.tex"
  stevejtrettel/course-notes-pdf:
    toc: true
    include-in-header: 
      - "_formatting/macros.tex"