project:
  type: book

book:
  title: "Reaching for Infinity"
  author: "Steve Trettel"
  date: today
  downloads: [pdf]
  
  chapters:
    - index.qmd
    
    - part: "The Real Numbers"
      chapters:
        - chapters/01-foundations/index.qmd
        - chapters/02-limits/index.qmd
        - chapters/03-detecting-convergence/index.qmd
        - chapters/04-exchanging-limits/index.qmd
        
    - part: "Functions"
      chapters:
        - chapters/05-continuity/index.qmd
        - chapters/06-differentiation/index.qmd
        - chapters/07-integration/index.qmd
        - chapters/08-calculus/index.qmd
        - chapters/09-complete-integral/index.qmd

    - part: "Function Space"
      chapters:
        - chapters/10-metrics/index.qmd
        - chapters/11-function-space/index.qmd
        - chapters/12-fourier/index.qmd
        - chapters/13-topics/index.qmd

        
format:
  stevejtrettel/course-notes-html:
    include-before-body: 
       - "_formatting/dollar.tex"
       - "_formatting/macros.tex"
       - "_formatting/dollar.tex"
  stevejtrettel/course-notes-pdf:
    toc: true
    include-in-header: 
      - "_formatting/macros.tex"