project:
  type: book

book:
  title: "Reaching for Infinity"
  author: "Steve Trettel"
  date: today
  downloads: [pdf]
  
  chapters:
    - index.qmd

format:
  stevejtrettel/course-notes-html: default
  stevejtrettel/course-notes-pdf: default