- Chapter 1: We asked "what is $\mathbb{R}$?" Answer: complete ordered field
- Now: What are spaces of functions? What structure do they have?
- Same questions: completeness, convergence, optimization, density
- Multiple families: $C^k$ (differentiability), $L^p$ (integrability)
- Different norms measure different things
